### ISSUE TITLE
Windows: Broken file output because of newline translation

### ISSUE THREAD

**Issue by tomolt** [lhf/libschrift-show#1]
Hi,

First off thank you for providing this demo program!

I've noticed that on Windows, it produces skewed images such as this one:
![libschrift-show](https://github.com/lhf/libschrift-show/assets/6959624/4583f02a-9752-469d-85e1-afc334e177e8)
This is because your demo writes binary pixel values to stdout, which typically contain some 0x0A (Line Feed) bytes here and there.
Because Windows uses CR LF newlines, and stdout is usually in text mode (think `fopen(,"w")`, as opposed to `fopen(,"wb"))`,
these 0x0A bytes will be replaced by a 0x0D 0x0A (CR LF) sequence during `fwrite()`.
Consider writing images to a file instead of to the console.
Alternatively, you could use something like `setmode(fileno(stdout), O_BINARY)` on Windows to force stdout into binary mode.

**Comment by lhf** [comment]
Thanks for trying my demo program. And for your work on libschrift!

I had only tested my program on macOS and Linux, where they work fine. I never tried Windows.

There doesn't seem to be a [portable way to put stdout in binary mode](https://stackoverflow.com/questions/40609260/portable-way-to-put-stdout-in-binary-mode).

I'll probably end up writing to a binary file, which is sure to be portable.

**Comment by lhf** [comment]
It's fixed. Thanks for the report.
